### ISSUE TITLE
Hitting a timeout shouldn't abort the health check

### ISSUE THREAD

**Issue by toolforger** [antoinemeyer/spring-boot-async-health-indicator#2]
Health check taking longer than the expected timeout isn't a reason to abort the check; it may still succeeds a while later.

Suggestion: Just report the status as DOWN until the health check returns.

(Background: Interrupting the background check would kill the MongoDB template, which would abort the entire server startup.)

**Comment by antoinemeyer** [comment]
Thanks for filing this issue, it is a legitimate usecase.
The ability to opt out from thread interruption in healthchecks will be added in https://github.com/antoinemeyer/spring-boot-async-health-indicator/pull/3

**Comment by antoinemeyer** [comment]
Please update version to `boot2-v1.2` and add `interruptOnTimeout = false` to your health indicator to disable thread interruption.
